### ISSUE TITLE
prefixes with '.' not working

### ISSUE THREAD

**Issue by sarala** [identifiers-org/cloud-ws-resolver#21]
http://resolver.api.aws.identifiers.org/kegg.module:M00002

**Comment by mbdebian** [comment]
I think we have a problem here, because **most** (if not all) MVC frameworks (Spring, Django, etc.) will interpret that last dot as content negotiation (based on suffixes), and the drawbacks from changing this will probably outweight the benefits.

We should probably evaluate how many use cases we have for this before we take a decision on what to do about it.

What do you think @sarala ?

**Comment by mbdebian** [comment]
@sarala , I'm working on this issue, could you provide more examples with dots on either the namespace, the ID or both of them?
Thanks ☺️

**Comment by mbdebian** [comment]
This is working in the test environment with the new URL routing mechanism.
